version: '3'
services:
  eureka:
    build: ./eureka-service
    ports:
      - 8282:8282
  zuul:
    build: ./zuul-service
    ports:
      - 5000:5000
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - eureka
  auth:
    build: ./auth-service
    ports:
      - 5010:5010
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - zuul
  queuefv:
    build:
      context: ./queue-service
      args:
        PORT: 5020
    environment:
      - "SPRING_PROFILES_ACTIVE=fv,docker"
    ports:
      - 5020:5020
    depends_on:
      - zuul
  queuevf:
    build:
      context: ./queue-service
      args:
        PORT: 5030
    environment:
      - "SPRING_PROFILES_ACTIVE=vf,docker"
    ports:
      - 5030:5030
    depends_on:
      - zuul
  trip:
    build: ./trip-service
    ports:
      - 5040:5040
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - zuul
  turbine:
    build: ./turbine-service
    ports:
      - 5050:5050
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - auth
      - queuefv
      - queuevf
      - trip
  client:
    build: ../local-taxi-client
    ports:
      - 4200:4200
    depends_on:
      - eureka
      - zuul
      - auth
      - queuefv
      - queuevf
      - trip
