server:
  port: 5040

spring:
  profiles:
    active: local
  application:
    name: trip-service
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/database_changelog.xml
