spring:
  profiles:
    active: local
  application:
    name: turbine-service

server:
  port: 5050

turbine:
  app-config: auth-service,queue-fv-service,queue-vf-service,trip-service
  cluster-name-expression: new String("default")
