server:
  port: 5000

spring:
  application:
    name: zuul-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka

ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 180000

zuul:
  sensitive-headers:
