server:
  port: 5010

spring:
  application:
    name: auth-service
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/database_changelog.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka
